// All claims, organizations, documents and measurements are fictional training data.
export const ADVANCED_CASES = [
  {
    id: "case_05", number: 5, difficulty: "Nâng cao", title: "AI và phép tính 40%", points: 4,
    correctVerdict: "MISLEADING", bestAction: "ADD_CONTEXT", reasonableActions: ["WAIT_FOR_MORE_EVIDENCE"],
    lesson: "Một kết quả đo được không tự chứng minh nguyên nhân hoặc áp dụng cho mọi người.",
    explanation: "20% so với 12% đúng là thấp hơn 40% theo tỷ lệ tương đối, nhưng chỉ chênh 8 điểm phần trăm. Hai nhóm tự chọn cách học, không được phân ngẫu nhiên; kết quả đo việc nhớ sáu trích dẫn ngay sau bài tập, không đo trí nhớ tổng thể. Tít bài mở rộng cả đối tượng, phép đo và quan hệ nhân quả.",
    pitfalls: ["Không thể đổi một bài kiểm tra cụ thể thành kết luận về mọi năng lực ghi nhớ.", "Bài trên một tạp chí uy tín vẫn có thể bị nguồn thứ cấp diễn giải quá mức."],
    post: {
      author: "Learning Monitor", handle: "@learningmonitor", time: "17 phút trước", marker: "NGHIÊN CỨU MỚI",
      headline: "Nghiên cứu: dùng AI khiến trí nhớ sinh viên giảm 40%",
      body: "Tạp chí Learning Methods vừa công bố nghiên cứu trên 120 sinh viên. Nhóm dùng trợ lý AI chỉ nhớ được 12% trích dẫn, so với 20% ở nhóm còn lại. Các chuyên gia cảnh báo tác động lâu dài của việc phụ thuộc công nghệ.",
      likes: "18,2K", comments: "2,1K", shares: "7,6K", media: "research", mediaAlt: "Đồ họa bài đăng so sánh 20% ở nhóm không dùng AI và 12% ở nhóm dùng AI, với tít giảm 40%.",
      caption: "Đồ họa do trang đăng bài tạo lại từ bản tóm tắt nghiên cứu.",
    },
    checks: [
      { id: "check_statistics", label: "Đối chiếu phép tính", cost: 1, score: 10, icon: "chart", title: "Hai cách biểu diễn cùng chênh lệch", evidence: "(20 − 12) / 20 = 40% giảm tương đối. Chênh lệch tuyệt đối là 8 điểm phần trăm. Cả hai con số đều có thể đúng, nhưng mô tả những thứ khác nhau.", note: "Xác định rõ mẫu số trước khi đánh giá độ lớn của một hiệu ứng.", source: "Bảng 2 · Learning Methods · bản mô phỏng", table: { columns: ["Nhóm", "Nhớ trích dẫn", "Cỡ nhóm"], rows: [["Không dùng AI", "20%", "60"], ["Dùng AI", "12%", "60"]] } },
      { id: "read_method", label: "Đọc phương pháp nghiên cứu", cost: 2, score: 20, strong: true, icon: "file", title: "Nhóm tự chọn, phép đo hẹp", evidence: "Sinh viên tự chọn dùng hay không dùng AI; không có phân nhóm ngẫu nhiên hoặc bài đo trước can thiệp. Chỉ số là khả năng nhớ sáu trích dẫn ngay sau một bài viết. Tác giả ghi: không thể suy ra suy giảm trí nhớ lâu dài.", note: "Thiết kế nghiên cứu quyết định những kết luận nó có thể hỗ trợ.", source: "Mục Phương pháp và Giới hạn · trang 4–6" },
      { id: "check_sample", label: "Kiểm tra người tham gia", cost: 1, score: 8, icon: "users", title: "Mẫu tuyển từ một môn tự chọn", evidence: "120 sinh viên thuộc một môn viết học thuật. Nhóm dùng AI có kinh nghiệm viết ít hơn theo phiếu tự khai; tác giả chưa điều chỉnh khác biệt này. Không có dữ liệu ở học sinh hay các ngành khác.", note: "Khác biệt có sẵn giữa hai nhóm có thể ảnh hưởng kết quả.", source: "Phụ lục A · thông tin tuyển mẫu" },
      { id: "check_source", label: "Kiểm tra tạp chí và tác giả", cost: 1, score: 4, icon: "globe", title: "Bài nghiên cứu có thật trong hồ sơ", evidence: "Tạp chí có ban biên tập, mã bài và phản biện. Learning Monitor dẫn đúng mã bài, nhưng câu về tác động lâu dài do trang tự thêm, không nằm trong abstract.", note: "Uy tín nguồn giúp truy tìm chứng cứ; không thay thế việc đọc đúng nội dung.", source: "Mục lục tạp chí · số 7" },
      { id: "compare_replication", label: "Tìm nghiên cứu đối chiếu", cost: 1, score: 10, strong: true, icon: "newspaper", title: "Kết quả khác ở bài kiểm tra khác", evidence: "Một thử nghiệm phân nhóm ngẫu nhiên với 80 người không thấy khác biệt ở bài nhớ khái niệm sau một tuần. Hai nghiên cứu dùng nhiệm vụ khác nhau, nên chưa thể xem nghiên cứu này đã bác bỏ nghiên cứu kia.", note: "Đối chiếu cả thiết kế và phép đo, không chỉ xem tiêu đề kết quả.", source: "Bản tóm tắt thử nghiệm R-08 · hồ sơ đối chiếu" },
      { id: "check_comments", label: "Xem trải nghiệm được chia sẻ", cost: 1, score: 2, icon: "messages", title: "Chứng thực trái chiều", evidence: "Một bình luận 5.000 lượt thích nói đã quên bài sau khi dùng AI. Một người khác nói kết quả thi tăng. Không bình luận nào đo đúng chỉ số của nghiên cứu hoặc tách được các nguyên nhân khác.", note: "Trải nghiệm cá nhân có giá trị gợi ý, nhưng không đủ để khái quát.", source: "Bình luận nổi bật · dữ liệu mô phỏng" },
    ],
  },
  {
    id: "case_06", number: 6, difficulty: "Nâng cao", title: "Bức ảnh đúng, chú thích sai", points: 3,
    correctVerdict: "FALSE", bestAction: "ADD_CONTEXT", reasonableActions: ["REPORT"],
    lesson: "Ảnh không chỉnh sửa vẫn có thể đi kèm một khẳng định sai về thời gian và địa điểm.",
    explanation: "Ảnh cho thấy một trận ngập có thật trong tình huống mô phỏng, nhưng bản gốc đã đăng từ 2023 tại cơ sở An Phú. Bài viral khẳng định đây là cơ sở Nam Sơn sáng nay. Kiến trúc, nhật ký ảnh và thông báo mở cửa xác nhận hai cơ sở khác nhau; vì vậy khẳng định cụ thể của bài là sai, dù ảnh không bị ghép.",
    pitfalls: ["Không phát hiện chỉnh sửa không xác nhận địa điểm hay thời điểm.", "Dự báo mưa đúng chỉ làm câu chuyện có vẻ hợp lý, chưa xác nhận bức ảnh."],
    post: {
      author: "Góc Campus", handle: "@goccampus", time: "9 phút trước", marker: "ẢNH TỪ SINH VIÊN",
      headline: "Cơ sở Nam Sơn ngập sáng nay; trường đã đóng cửa",
      body: "Ảnh được gửi lúc 07:20, cho thấy nước phủ kín sân và hàng xe đạp dưới mái che. Khu vực đang có cảnh báo mưa lớn. Nhiều sinh viên chia sẻ để bạn bè khỏi đến trường vô ích.",
      likes: "24,6K", comments: "3,8K", shares: "12,4K", media: "flood", mediaAlt: "Ảnh mô phỏng sân một trường đại học ngập nước, có mái che màu xanh và hàng xe đạp.",
      caption: "“07:20 · Nam Sơn · sáng nay” — chú thích của người đăng, chưa được kiểm chứng.",
    },
    checks: [
      { id: "reverse_image", label: "Tìm lần xuất hiện trước", cost: 2, score: 20, strong: true, icon: "image", title: "Ảnh trong album năm 2023", evidence: "Cùng ảnh và cùng vị trí xe đạp xuất hiện trong album ngày 18/09/2023 của cơ sở An Phú. Nhật ký lưu trữ độc lập ghi nhận album từ năm đó, trước bài hiện tại. Chú thích gốc nói về dọn sân sau mưa.", note: "Một dấu vết xuất bản sớm hơn là căn cứ để kiểm tra lại câu chuyện đi kèm ảnh.", source: "Album An Phú · bản lưu ngày 19/09/2023" },
      { id: "compare_location", label: "So khớp kiến trúc", cost: 1, score: 15, strong: true, icon: "landmark", title: "Hai cơ sở, hai kiểu mái", evidence: "Ảnh có mái thép xanh và lối nhà hình chữ U, khớp sơ đồ cơ sở An Phú. Sân Nam Sơn có mái kính, dãy nhà song song và không có khu xe đạp này.", note: "Dùng các đặc điểm ổn định để kiểm tra địa điểm.", source: "Sơ đồ và ảnh giới thiệu hai cơ sở" },
      { id: "check_official", label: "Kiểm tra lịch mở cửa", cost: 1, score: 10, icon: "calendar", title: "Lịch vận hành hôm nay", evidence: "Thông báo lúc 08:05 xác nhận Nam Sơn mở cửa bình thường; camera sảnh lúc 08:00 cho thấy lối vào khô ráo. Trường chưa có quyết định nghỉ hoặc đóng cửa do mưa.", note: "Nguồn trực tiếp phù hợp thời điểm giúp đối chiếu hệ quả của bài đăng.", source: "Bảng vận hành Nam Sơn · 08:05" },
      { id: "check_weather", label: "Đối chiếu thời tiết", cost: 1, score: 4, icon: "globe", title: "Mưa là thật, ảnh vẫn cần kiểm tra", evidence: "Trạm khu vực đo mưa lớn đêm qua; bản tin cảnh báo nguy cơ ngập ở các tuyến đường thấp. Không có ảnh từ trạm hoặc báo cáo ngập riêng cho sân Nam Sơn.", note: "Bối cảnh phù hợp không xác nhận mọi chi tiết của một khẳng định.", source: "Bản tin thời tiết mô phỏng · 06:00" },
      { id: "check_metadata", label: "Phân tích tệp ảnh", cost: 1, score: 5, icon: "fingerprint", title: "Không tìm thấy dấu ghép", evidence: "Tệp qua mạng xã hội đã mất EXIF. Công cụ không phát hiện vết ghép bất thường, nhưng không thể xác định ngày chụp hoặc nơi chụp từ tệp này.", note: "Không có dấu hiệu can thiệp và đã xác thực ngữ cảnh là hai việc khác nhau.", source: "Báo cáo phân tích tệp · độ phân giải 1536×1024" },
      { id: "check_comments", label: "Kiểm tra người chia sẻ", cost: 1, score: 2, icon: "messages", title: "Lời kể chưa xác định cơ sở", evidence: "Nhiều người nhận ra 'mái che của trường mình', nhưng chưa nói rõ cơ sở. Tài khoản gửi ảnh lần đầu không trả lời yêu cầu gửi vị trí hoặc ảnh khác cùng thời điểm.", note: "Chứng thực cần gắn với địa điểm, thời gian và khả năng quan sát thực tế.", source: "Luồng bình luận · 08:10" },
    ],
  },
  {
    id: "case_07", number: 7, difficulty: "Nâng cao", title: "Miễn phí có đúng là miễn phí?", points: 3,
    correctVerdict: "TRUE", bestAction: "SHARE", reasonableActions: ["ADD_CONTEXT"],
    lesson: "Đánh giá đúng phạm vi khẳng định; đừng bác bỏ chỉ vì tìm thấy một ngoại lệ bên ngoài phạm vi đó.",
    explanation: "Bài đăng nói chính xác tuyến nội bộ S1 trong ngày thường, chỉ với sinh viên và khi quét thẻ. Chính sách hiện hành và một lượt đặt vé độc lập đều xác nhận giá 0đ. Các phí xuất hiện trong bình luận thuộc tuyến S2 cuối tuần, thẻ thất lạc hoặc nhóm khách khác, không mâu thuẫn với khẳng định hẹp này.",
    pitfalls: ["Một ảnh hóa đơn chỉ có ý nghĩa khi đúng tuyến, đúng đối tượng và đúng thời điểm.", "Tìm thấy điều kiện áp dụng không làm sai một bài đã nêu rõ các điều kiện đó."],
    post: {
      author: "Đi cùng Campus", handle: "@dicungcampus", time: "36 phút trước", marker: "CẬP NHẬT ĐI LẠI",
      headline: "Sinh viên đi tuyến S1 nội bộ miễn phí ngày thường từ tháng này",
      body: "Áp dụng thứ Hai đến thứ Sáu giữa hai cơ sở An Phú và Nam Sơn, chỉ cần quét thẻ sinh viên còn hiệu lực. Tuyến S2 và chuyến cuối tuần vẫn theo biểu giá riêng. Phía dưới, một ảnh hóa đơn 20.000đ khiến nhiều người nghi ngờ thông báo.",
      likes: "7,3K", comments: "1,9K", shares: "4,2K", media: "shuttle", mediaAlt: "Thông tin tuyến S1 giữa An Phú và Nam Sơn, áp dụng thứ Hai đến thứ Sáu cho sinh viên với giá 0 đồng.",
      caption: "Bản tóm tắt tuyến S1, không phải thông báo cho mọi tuyến xe.",
    },
    checks: [
      { id: "read_policy", label: "Đọc chính sách hiện hành", cost: 2, score: 20, strong: true, icon: "file", title: "Điều 3, bảng giá đang hiệu lực", evidence: "Văn bản 24/SV có hiệu lực từ ngày 01 tháng này: tuyến S1, thứ Hai–thứ Sáu, sinh viên có thẻ hợp lệ: 0đ/lượt. S2, chuyến cuối tuần và khách ngoài trường có bảng giá riêng.", note: "So sánh từng điều kiện trong văn bản với từng điều kiện trong bài đăng.", source: "Văn bản 24/SV · Điều 3", table: { columns: ["Tuyến / đối tượng", "Ngày", "Giá"], rows: [["S1 / sinh viên", "T2–T6", "0đ"], ["S2 / sinh viên", "T7–CN", "20.000đ"], ["S1 / khách", "T2–T6", "10.000đ"]] } },
      { id: "check_ticket", label: "Kiểm tra lượt đặt thực tế", cost: 1, score: 15, strong: true, icon: "scan", title: "Đặt vé khớp chính sách", evidence: "Biên nhận trên ứng dụng: S1, An Phú → Nam Sơn, thứ Ba tuần này, tài khoản sinh viên được xác thực, tổng giá 0đ. Nhật ký xác nhận quét thẻ tại cổng lên xe.", note: "Quan sát độc lập chỉ hỗ trợ khẳng định trong đúng phạm vi đã kiểm tra.", source: "Biên nhận T-173 · dữ liệu cá nhân đã ẩn" },
      { id: "check_receipt", label: "Đọc hóa đơn gây tranh cãi", cost: 1, score: 10, icon: "image", title: "20.000đ cho một chuyến khác", evidence: "Ảnh hóa đơn đầy đủ ghi S2, chuyến thứ Bảy. Phần này bị cắt khỏi ảnh bình luận. Hóa đơn là thật, nhưng không phải lượt đi S1 trong ngày thường.", note: "Xác thực tệp và xác thực tính liên quan cần được làm riêng.", source: "Hóa đơn S2-204 · bản đầy đủ" },
      { id: "check_source", label: "Kiểm tra đơn vị vận hành", cost: 1, score: 5, icon: "landmark", title: "Đơn vị vận hành xác nhận", evidence: "Trang tuyến xe chính thức liên kết văn bản 24/SV và công bố S1 giá 0đ cho đúng nhóm người dùng. Trang thông báo cũng liệt kê phí làm lại thẻ 50.000đ nếu bị mất.", note: "Một phí khác cùng trang không tự động trở thành giá vé của tuyến đang xét.", source: "Trang vận hành tuyến S1 · cập nhật tháng này" },
      { id: "check_old_policy", label: "Xem quy định năm trước", cost: 1, score: 3, icon: "calendar", title: "Biểu giá cũ 10.000đ", evidence: "Một PDF năm trước ghi S1 giá 10.000đ/lượt. Trang lưu trữ gắn trạng thái 'đã thay thế bởi 24/SV'. Tệp cũ vẫn xuất hiện cao trong kết quả tìm kiếm.", note: "Nguồn chính thức vẫn cần được kiểm tra hiệu lực theo thời gian.", source: "Kho văn bản lưu trữ · bản hết hiệu lực" },
      { id: "check_comments", label: "Đọc phản hồi hành khách", cost: 1, score: 2, icon: "messages", title: "Những chi phí khác nhau", evidence: "Người nói mất 50.000đ đang làm lại thẻ; người trả 20.000đ đi cuối tuần. Một sinh viên đi S1 hôm qua báo giá 0đ nhưng không đăng biên nhận.", note: "Tách giá vé, phí thẻ và điều kiện chuyến trước khi so sánh.", source: "Luồng hỏi đáp tuyến xe" },
    ],
  },
  {
    id: "case_08", number: 8, difficulty: "Khủng hoảng", title: "Giọng nói giống chưa đủ", points: 4, timerSeconds: 120,
    correctVerdict: "NOT_ENOUGH_EVIDENCE", bestAction: "WAIT_FOR_MORE_EVIDENCE", reasonableActions: ["ADD_CONTEXT"],
    lesson: "Một công cụ cho xác suất không thay thế nguồn gốc và chuỗi xác thực của bằng chứng.",
    explanation: "Đoạn âm thanh chưa có tệp gốc, nguồn cung cấp hoặc bản họp đầy đủ. Nhận diện giọng nói không xác nhận bối cảnh; công cụ deepfake chỉ cho chỉ số không được hiệu chỉnh cho tiếng Việt và cho kết quả không nhất quán. Phủ nhận của trường cũng chưa được đối chiếu độc lập. Chưa đủ cơ sở xác nhận hoặc bác bỏ tăng học phí 25%.",
    pitfalls: ["'87% giống giọng' không có nghĩa '87% khả năng lời nói là thật'.", "Chưa tìm thấy văn bản và sự việc chắc chắn không tồn tại là hai kết luận khác nhau."],
    post: {
      author: "Campus Insider", handle: "@campusinsider", time: "4 phút trước", marker: "ĐOẠN GHI ÂM LAN TRUYỀN",
      headline: "Ghi âm họp kín: học phí sẽ tăng 25% học kỳ tới?",
      body: "Đoạn cắt 18 giây có giọng giống lãnh đạo: 'mức điều chỉnh hai mươi lăm phần trăm... từ học kỳ tới'. Người gửi nói trích từ một cuộc họp nội bộ. Một công cụ nhận diện trả kết quả giống giọng 87%; nhà trường nói chưa có quyết định tăng.",
      likes: "39,8K", comments: "8,1K", shares: "22,5K", media: "audio", mediaAlt: "Đồ họa đoạn ghi âm mô phỏng dài 18 giây, cùng trích đoạn chưa có bối cảnh đầy đủ.",
      caption: "Bản chép lời mô phỏng; không có file âm thanh thật để xác minh nguồn.",
    },
    checks: [
      { id: "trace_recording", label: "Truy nguồn bản ghi", cost: 2, score: 20, strong: true, icon: "file", title: "Chưa có tệp gốc hay người chịu trách nhiệm", evidence: "Bản chia sẻ sớm nhất tìm được là một tài khoản ẩn danh. Không cung cấp tệp gốc, thời gian, phòng họp hoặc người ghi. Các bản đăng sau cùng một đoạn cắt, không phải các nguồn chứng thực độc lập.", note: "Nhiều bản sao có thể cùng bắt nguồn từ một thông tin chưa được kiểm chứng.", source: "Sơ đồ lan truyền · 11 bản đăng lại" },
      { id: "check_detector", label: "Đọc giới hạn công cụ", cost: 1, score: 15, strong: true, icon: "fingerprint", title: "Điểm giống giọng không phải xác suất thật", evidence: "87% là độ tương đồng giọng so với một đoạn công khai, không đánh giá câu nói, ngày họp hay cắt ghép. Công cụ deepfake A báo 62% synthetic, B báo 31%; cả hai ghi mẫu ngắn và tiếng Việt nằm ngoài bộ đánh giá chuẩn.", note: "Trước khi dùng con số làm bằng chứng, hỏi chính xác nó đang đo điều gì.", source: "Thẻ mô hình và báo cáo phân tích · bản mô phỏng" },
      { id: "find_minutes", label: "Tìm biên bản và bản đầy đủ", cost: 2, score: 15, strong: true, icon: "newspaper", title: "Đối tượng của 25% chưa rõ", evidence: "Chưa tìm được biên bản có câu tương ứng. Lịch họp tuần này gồm học phí, học bổng và phí ký túc xá. Không có đoạn trước hoặc sau để xác định '25%' nói về mục nào hay là một đề xuất.", note: "Một phát biểu bị cắt mất chủ ngữ hoặc đối tượng có nhiều cách diễn giải.", source: "Lịch họp và yêu cầu cung cấp biên bản" },
      { id: "check_official", label: "Đối chiếu thông báo của trường", cost: 1, score: 10, icon: "landmark", title: "Chưa có quyết định được công bố", evidence: "Trường nói chưa ban hành quyết định tăng học phí và đang rà soát đoạn ghi âm. Họ chưa công bố bản gốc hoặc biên bản để đối chiếu. Thông báo không xác nhận đoạn này là giả.", note: "Tuyên bố của bên liên quan cần được đặt cạnh bằng chứng độc lập.", source: "Thông báo phòng thông tin · 09:15" },
      { id: "check_budget", label: "Xem kế hoạch ngân sách", cost: 1, score: 5, icon: "chart", title: "Chi phí tăng, nguồn thu chưa chốt", evidence: "Dự toán chi vận hành tăng 12%; tài liệu nói có thể dùng quỹ dự phòng hoặc điều chỉnh nguồn thu. Không ghi con số 25%, đối tượng thu hoặc học kỳ áp dụng.", note: "Một động cơ có thể có không chứng minh một quyết định cụ thể đã xảy ra.", source: "Dự toán sơ bộ · trang 2" },
      { id: "check_comments", label: "Kiểm tra lời kể người nghe", cost: 1, score: 2, icon: "messages", title: "Nhận ra giọng, không chứng kiến cuộc họp", evidence: "Các bình luận nói đã nghe giọng này trong lễ khai giảng. Không người nào xác nhận mình dự cuộc họp hoặc có bản ghi dài hơn. Một tài khoản đăng 'nguồn riêng' lại dẫn đúng bài của Campus Insider.", note: "Nhận dạng người nói và xác nhận sự kiện là hai tầng bằng chứng khác nhau.", source: "Luồng bình luận · nguồn đã đối chiếu" },
    ],
  },
];
